version: 0.2

env:
  variables:
    ECR_HOST: "AWS-ID.dkr.ecr.REGION.amazonaws.com"
    APP_NAME: "PJ-NAME-APP-NAME"
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - if [ $(date -d $APP_RELEASE_DATE +%s) -gt $(date -d $ECS_RELEASE_DATE +%s) ];then export IS_APP_TRIGGERED=true;else export IS_APP_TRIGGERED=false;fi
      - if "${IS_APP_TRIGGERED}" ;then aws ecr get-login-password --region REGION | docker login --username AWS --password-stdin $ECR_HOST;fi
  build:
    commands:
      - if "${IS_APP_TRIGGERED}" ;then docker build -t $ECR_HOST/$APP_NAME:latest .;fi
      - if "${IS_APP_TRIGGERED}" ;then docker push $ECR_HOST/$APP_NAME:latest;fi
  post_build:
    commands:
      - printf '{"Version":"1.0","ImageURI":"%s"}' $ECR_HOST/$APP_NAME:latest > imageDetail.json

artifacts:
  files: imageDetail.json