version: 0.2

env:
  variables:
    ECR_HOST: "AWS-ID.dkr.ecr.REGION.amazonaws.com"
    APP_NAME: "PJ-NAME-APP-NAME"
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws ecr get-login-password --region REGION | docker login --username AWS --password-stdin $ECR_HOST
  build:
    commands:
      - docker build -t $ECR_HOST/$APP_NAME:latest .
      - docker push $ECR_HOST/$APP_NAME:latest
  post_build:
    commands:
      - printf '{"Version":"1.0","ImageURI":"%s"}' $ECR_HOST/$APP_NAME:latest > imageDetail.json

artifacts:
  files: imageDetail.json